### PR TITLE
changes VCF as expected

### PR DESCRIPTION
**Pull request by aledj2**
ignore the changes made to version numbers!

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9)

### CODE REVIEW

**Comment by aledj2** [comment]
have resolved conflicts but not tested

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[dxapp.json, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9#-M77NMMAEsF6nXoq7FgL:-M77NMMAEsF6nXoq7FgM:bd0n23m) ([raw file](https://github.com/moka-guys/dnanexus_vardict/blob/e004a5bffae79ea169a461f2e2d0702f50f2bafa/dxapp.json#L1)):*
> ```JSON
> 
> ```

I think you need to keep the opening { for it to be a valid JSON file.

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[dxapp.json, line 1 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9#-M77NMMAEsF6nXoq7FgL:-M77PeB0DdeUGpGSmFwU:b7ay5nk) ([raw file](https://github.com/moka-guys/dnanexus_vardict/blob/e004a5bffae79ea169a461f2e2d0702f50f2bafa/dxapp.json#L1)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I think you need to keep the opening { for it to be a valid JSON file.
</blockquote></details>

good spot

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_vardict/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
